version: 2.1
jobs:
  test:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
workflows:
  build_and_test:
    jobs:
      - test:
          name: "Test against Ruby 3.1"
          ruby_version: "3.1"
      - test:
          name: "Test against Ruby 3.2"
          ruby_version: "3.2"
      - test:
          name: "Test against Ruby 3.3"
          ruby_version: "3.3"
