version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7

    working_directory: ~/intercom-ruby

    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
