# frozen_string_literal: true

require 'intercom/version'
require 'intercom/service/admin'
require 'intercom/service/article'
require 'intercom/service/company'
require 'intercom/service/contact'
require 'intercom/service/conversation'
require 'intercom/service/count'
require 'intercom/service/event'
require 'intercom/service/message'
require 'intercom/service/note'
require 'intercom/service/job'
require 'intercom/service/subscription'
require 'intercom/service/segment'
require 'intercom/service/tag'
require 'intercom/service/team'
require 'intercom/service/visitor'
require 'intercom/service/user'
require 'intercom/service/lead'
require 'intercom/deprecated_resources.rb'
require 'intercom/options'
require 'intercom/client'
require 'intercom/contact'
require 'intercom/user'
require 'intercom/lead'
require 'intercom/count'
require 'intercom/company'
require 'intercom/service/data_attribute'
require 'intercom/note'
require 'intercom/job'
require 'intercom/tag'
require 'intercom/segment'
require 'intercom/event'
require 'intercom/conversation'
require 'intercom/message'
require 'intercom/admin'
require 'intercom/article'
require 'intercom/request'
require 'intercom/subscription'
require 'intercom/team'
require 'intercom/errors'
require 'intercom/visitor'
require 'intercom/data_attribute'
require 'json'

##
# Intercom is a customer relationship management and messaging tool for web app owners
#
# This library provides ruby bindings for the Intercom API (https://api.intercom.io)
module Intercom
end
